# Generated by Django 4.1.2 on 2022-10-19 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0003_accountws"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Accountws",
        ),
    ]
